### ISSUE TITLE
The canvasXpess plot title and subtitle look much bigger than they should be? 

### ISSUE THREAD

**Issue by davidhodge931** [neuhausi/canvasXpress#152]
```
library(tidyverse)
library(palmerpenguins)
library(ggblanket) # v7
library(canvasXpress)

set_blanket()

p <- penguins |>
  mutate(across(sex, \(x) stringr::str_to_sentence(x))) |>
  gg_point(
    x = flipper_length_mm,
    y = body_mass_g,
    col = species,
    title = "Blah",
    subtitle = "Blah",
    col_title = "Blah",
  )

p

canvasXpress::canvasXpress(p)
```

**Comment by neuhausi** [comment]
Fixed is next version. However it is not going to be exactly as ggplot since ggplot does not scale properly when the size of the graph is changed. Here are two examples
  
![cX-htmlwidget-db2114ff29b7d3ae7020-cx](https://github.com/neuhausi/canvasXpress/assets/254923/ed484470-3b1a-4be4-b356-905183d0c2d2)

![cX-htmlwidget-db2114ff29b7d3ae7020-cx (2)](https://github.com/neuhausi/canvasXpress/assets/254923/9481dc6f-8c6a-45fa-8d43-8bcd06e5325b)

**Comment by davidhodge931** [comment]
In my {ggblanket} plot, I make the plot title 10% bigger than the size selected for everything else.

I default to 11, and so the plot title ends up defaulting to 12.1.

It'd be cool, if canvasXpress could respect this?

**Comment by davidhodge931** [comment]
Nice :)
