### ISSUE TITLE
Filtering checkboxes 

### ISSUE THREAD

**Issue by alin-png** [neuhausi/canvasXpress#172]
Hi Isaac, 

I wonder why checkboxes are available in the filtering view for some columns and not for others. For example in the image below:
<img width="338" alt="image" src="https://github.com/user-attachments/assets/1f8449a6-79e0-4294-bb9e-37968d0f4331">

I can select multiple 'type's using the checkboxes but I cannot do the same for the 'target's. The variables are declared the same way and I notice when I replace data.x.target with the data for data.x.type, the checkboxes are made available. Could this be because there are too many options available? Thanks!

**Comment by neuhausi** [comment]
It is based on the number of entries. It there are more than I believe seven it becomes a selection widget. Should I change this?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Angela ***@***.***>
Sent: Monday, September 16, 2024 3:30:18 AM
To: neuhausi/canvasXpress ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [neuhausi/canvasXpress] Filtering checkboxes (Issue #172)


Hi Isaac,

I wonder why checkboxes are available in the filtering view for some columns and not for others. For example in the image below:
image.png (view on web)<https://github.com/user-attachments/assets/1f8449a6-79e0-4294-bb9e-37968d0f4331>

I can select multiple 'type's using the checkboxes but I cannot do the same for the 'target's. The variables are declared the same way and I notice when I replace data.x.target with the data for data.x.type, the checkboxes are made available. Could this be because there are too many options available? Thanks!

**Comment by alin-png** [comment]
Thank you for your reply @neuhausi , it would be wonderful to be able to have the checkboxes available no matter the number of entries and also have the search bar that the selection widget uses too (so a user can select different options by searching up the name instead of scrolling through all the options available). However, I am conscious of other users of CanvasXpress, if you change this and it impacts their experience? what do you think? thank you :)

**Comment by neuhausi** [comment]
I will create a parameter so users can decide 😀

Isaac Neuhaus PhD.
