### ISSUE TITLE
Is the website/email link still the way to get the new Javascript library?

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasXpress#30]
I've noticed that a lot of the effort lately has been on the R package, but I'm still using and updating the good ol' Javascript library, which it seems must come from submitting the form on the website and getting the link which has fresh files behind it, to avoid the "R Version" watermark, or whatever it says. Is this still the way to get the JS and CSS files?

**Comment by neuhausi** [comment]
www.canvasxpress.org is the preferred way to get the latest code. The R version has some different hooks for R and some things  collide between R and non-R environments. BTW, the R package is being further developed because our need to work in a reproducible research environment but the base code JS and CSS is basically the same. Github and canvasxpress.org are in sync.
