### ISSUE TITLE
Plots not appearing in R Studio viewer

### ISSUE THREAD

**Issue by diegobah** [neuhausi/canvasXpress#65]
Hi, canvasxpress plots generated from the R studio console/scripts fail to initialize in the viewer as below (circles traveling around a zero). This issue seems to be specific to my current Windows OS install as its working on another PC. What would be the most likely environment issue to cause this?

If I click the "open in new window" button it successfully loads the plot in a browser window. 

![capture2](https://user-images.githubusercontent.com/44279302/47601667-5a5dcd80-da17-11e8-9122-fb1012b33220.PNG)

**Comment by neuhausi** [comment]
What version of R-Studio? Have you tried upgrading your R-Studio version? I had to implement many native JavaScript functions to be compatible with R-Studio because QT (which is the framework used to build R-Studio) uses a very old version of Chromium. I told the people of R-Studio and hopefully will be upgraded soon!.
Can you right click in the viewer and check for any errors in the console? 
Regards,
Isaac

**Comment by neuhausi** [comment]
Please let me know if you need any help with this. In the meantime I will close this issue.
