### ISSUE TITLE
Heatmap: Data transformation bug on color indicator

### ISSUE THREAD

**Issue by baohongz** [neuhausi/canvasXpress#72]
Please perform "log2" transformation and then transform back by "Exp Base 2", pay attention to color indicator on top and side.

http://canvasxpress.org/html/heatmap-10.html

**Comment by neuhausi** [comment]
The data transformation is intended to work on the original data rather than the current transformation. This way you can cycle through different transformation without resetting it every time.
My guess is that you were expecting to have the original data? the Exp Base 2 will cancel the log2, right?
In order to do that you would have to save the data first. This is done by design!
Thank you.
Isaac

**Comment by baohongz** [comment]
My guess is that you were expecting to have the original data? the Exp Base 2 will cancel the log2, right?
Yes. 
Ok. Now I understand the intended design.
